runtime: python311

service: rocaleda-fp-ms-users

entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

readiness_check:
    path: "/health"  
    check_interval_sec: 300
    timeout_sec: 300  
    failure_threshold: 5

env_variables:
    DB_URL: VAR_DB_URL
    CANDIDATE_CREATION_TOPIC: VAR_CANDIDATE_CREATION_TOPIC
    GOOGLE_CLOUD_PROJECT: VAR_PROJECT_ID

vpc_access_connector:
    name: projects/VAR_PROJECT_ID/locations/VAR_REGION/connectors/VAR_VPC_CONNECTOR
    egress_setting: all-traffic
